name: Run Python unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  schedule:
  - cron: '*/5 * * * *'


jobs:
  test:
    if: github.event_name == 'schedule' || github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover ./ '*_test.py'